pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'nylium'

include 'nylium-api'
include 'nylium-core'
include 'nylium-bootstrap-fabric'
include 'nylium-bootstrap-launchwrapper'
include 'nylium-bootstrap-modlauncher8'
include 'nylium-bootstrap-modlauncher9'
include 'nylium-gradle'
include 'nylium-testmod'
include 'smoke'
