pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'rutter'

include 'rutter-api'
include 'rutter-core'
include 'rutter-bootstrap-fabric'
include 'rutter-bootstrap-launchwrapper'
include 'rutter-bootstrap-modlauncher8'
include 'rutter-bootstrap-modlauncher9'
include 'rutter-testmod'
include 'smoke'
